In [2]:
#q1
import numpy as np
arr1 = np.array([9, 8, 7, 5])
arr2 = np.array([[2, 1], [4, 6]])
res = arr1.reshape(2,2)
result = np.concatenate((res, arr2), axis=0)
print("Result of concatenation along axis 0:\n", result)

Result of concatenation along axis 0:
 [[9 8]
 [7 5]
 [2 1]
 [4 6]]


In [4]:
#q2
arr = np.array([[5,4,2], [7,8,9]])
print(arr)
newarr = arr.reshape(-1)
print(newarr)

[[5 4 2]
 [7 8 9]]
[5 4 2 7 8 9]


In [ ]:
#q3
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr[-1::-1])

[12 11 10  9  8  7  6  5  4  3  2  1]


In [7]:
#q4
rr = np.array([1212,24,48,45,6])


print("Array:", rr)
print("Maximum Value:", np.max(rr))
print("Minimum Value:", np.min(rr))
for i in rr:
    print(i)


Array: [1212   24   48   45    6]
Maximum Value: 1212
Minimum Value: 6
1212
24
48
45
6


In [5]:
#q4
arrg = np.array([[10, 20, 30],
                [40, 50, 60]])

print("Element at row 1, column 2:", arrg[1, 2])
total = 0
rows, cols = arrg.shape
for row in arrg:
    for value in row:
        total += value
print("Rows:", rows)
print("Columns:", cols)
print("Array:")
print(arrg)
print("Sum =", total)

Element at row 1, column 2: 60
Rows: 2
Columns: 3
Array:
[[10 20 30]
 [40 50 60]]
Sum = 210


In [11]:
#q4
a = np.array([100,200,200])
b = np.array([1, 2, 4])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [101 202 204]
Subtraction: [ 99 198 196]
Multiplication: [100 400 800]
Division: [100. 100.  50.]


In [13]:
#q5
res1 = np.array([
    [[100,200], [300, 400]],
    [[500, 600], [700, 800]]
])
for i in res1:
    for j in i:
        for k in j:
             print(k)

100
200
300
400
500
600
700
800


In [17]:
#q5
pd = np.array([
    [[90,91], [92,93]],
    [[94,95], [96,97]]
])
for element in np.nditer(pd):
    print(element)

90
91
92
93
94
95
96
97


In [6]:
#q6
arr1 = np.array([90 , 91]) 
arr2 = np.array([89 , 99])
avg = (arr1 + arr2) / 2
print("Average of NumPy arrays:\n", avg)
print("Mean of the both array is  : " , avg.mean())

Average of NumPy arrays:
 [89.5 95. ]
Mean of the both array is  :  92.25


In [19]:
#q6
import pandas as pd
arr1 = np.array([
    [[41 , 42], [43, 44]],
    [[45, 46], [47, 48]]
])
arr2 = np.array([
    [[29, 30], [31, 32]],
    [[33, 34], [35, 36]]
])
avg = (arr1 + arr2) / 2

mode = pd.Series(avg.reshape(-1)).mode()
print("Average of NumPy arrays:\n", avg)
print("\nMean of avg\n",np.mean(avg))
print("\n Median of avg\n",np.median(avg))
print("\nMode of avg\n",mode)


Average of NumPy arrays:
 [[[35. 36.]
  [37. 38.]]

 [[39. 40.]
  [41. 42.]]]

Mean of avg
 38.5

 Median of avg
 38.5

Mode of avg
 0    35.0
1    36.0
2    37.0
3    38.0
4    39.0
5    40.0
6    41.0
7    42.0
dtype: float64
