In [4]:
#q1
import pandas as pd
import numpy as np
a = np.array([[9, -6, 12, -210], [np.nan, -14, 90, 92]])
print("Array")
print(a)
df = pd.DataFrame(a)
print("\nAfter replacing nan with Zero\n")
print(df.replace({np.nan:0}))
arr = np.resize(df, (3,3))
print("\nIn 3*3 Size\n",arr)
arr = arr.T
print("\ntranspose\n\n",arr)

Array
[[   9.   -6.   12. -210.]
 [  nan  -14.   90.   92.]]

After replacing nan with Zero

     0     1     2      3
0  9.0  -6.0  12.0 -210.0
1  0.0 -14.0  90.0   92.0

In 3*3 Size
 [[   9.   -6.   12.]
 [-210.   nan  -14.]
 [  90.   92.    9.]]

transpose

 [[   9. -210.   90.]
 [  -6.   nan   92.]
 [  12.  -14.    9.]]


In [5]:
#q2
import numpy as np

arr = np.array([
    [[7,8,9],
     [3,2,1],
     [13,14,15],
     [19,20,21]],

    [[7,8,9],
     [10,11,12],
     [16,17,18],
     [22,23,24]]
])

print("\n\n",arr,arr.shape)
a = np.moveaxis(arr,0,2)
print("\n\n",a,a.shape)




 [[[ 7  8  9]
  [ 3  2  1]
  [13 14 15]
  [19 20 21]]

 [[ 7  8  9]
  [10 11 12]
  [16 17 18]
  [22 23 24]]] (2, 4, 3)


 [[[ 7  7]
  [ 8  8]
  [ 9  9]]

 [[ 3 10]
  [ 2 11]
  [ 1 12]]

 [[13 16]
  [14 17]
  [15 18]]

 [[19 22]
  [20 23]
  [21 24]]] (4, 3, 2)


In [6]:
#q3
a = np.array([
    [11,21,np.nan],
    [32,np.nan,45],
    [np.nan,58,67]
    ])

df = pd.DataFrame(a)
print(df)
df.fillna(df.mean(),inplace=True)
print(df) 

      0     1     2
0  11.0  21.0   NaN
1  32.0   NaN  45.0
2   NaN  58.0  67.0
      0     1     2
0  11.0  21.0  56.0
1  32.0  39.5  45.0
2  21.5  58.0  67.0


In [7]:
#q4
a = np.array([[60, -85, 72, -121], [np.nan, -845, 90, 922]])
df = pd.DataFrame(a)
df.replace([-8,-110],0,inplace=True)
print(df)


      0      1     2      3
0  60.0  -85.0  72.0 -121.0
1   NaN -845.0  90.0  922.0
